backend:
  # Use netlify identity as backend
  #name: git-gateway
  #branch: master
  ### enable below lines for github integration ###
  name: github
  repo: rknightuk/rknight.me
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    path: '{{year}}/{{slug}}'
    create: true
    nested:
      depth: 2
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string", }
      - { label: "Permalink", name: "permalink", widget: "string", default: '{{ year }}/index.html' }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ['ActivityPub', 'AdventOfCode', 'AI', 'Alfred', 'Apps', 'BabyKnight', 'Development', 'DIY', 'Eleventy', 'Food', 'Games', 'Hackathon', 'Homescreen', 'Lego', 'Letters', 'MacOS', 'Mastodon', 'Movies', 'Music', 'OpenWeb', 'Personal', 'Podcasting', 'Recipes', 'Shortcuts', 'SocialMedia', 'StJude', 'TV', 'YearInReview']
    sortable_fields: ['date', 'title']
    summary: "{{title}} {{ date }}"
  - label: "Links"
    name: "links"
    folder: "src/links"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "description", widget: "markdown" }